export const SIGNIN = 'SIGNIN'; 
export const AUTHENTICATED = 'AUTHENTICATED';
export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SHOW_AUTH_MESSAGE = 'SHOW_AUTH_MESSAGE'
export const HIDE_AUTH_MESSAGE = 'HIDE_AUTH_MESSAGE'
export const SHOW_LOADING = 'SHOW_LOADING'
export const AUTH_TOKEN = 'auth_token'
export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE'
export const SIGNIN_WITH_GOOGLE_AUTHENTICATED = 'SIGNIN_WITH_GOOGLE_AUTHENTICATED'
export const SIGNIN_WITH_FACEBOOK = 'SIGNIN_WITH_FACEBOOK'
export const SIGNIN_WITH_FACEBOOK_AUTHENTICATED = 'SIGNIN_WITH_FACEBOOK_AUTHENTICATED'
export const UPDATE_USER ='UPDATE_USER'


export const ROLE_USER = "ROLE_USER";
export const ROLE_PLAYER = "ROLE_PLAYER";
export const ROLE_SHOP = "ROLE_SHOP";
export const ROLE_COMERCIAL = "ROLE_COMERCIAL";
export const ROLE_DEALER = "ROLE_DEALER";
export const ROLE_VALIDATOR = "ROLE_VALIDATOR";
export const ROLE_MASTER = "ROLE_MASTER";

export const Role_hierarchy = [
 /*  ROLE_USER,
  ROLE_PLAYER,
  ROLE_SHOP,
  ROLE_COMERCIAL,
  ROLE_DEALER,
  ROLE_VALIDATOR,
  ROLE_MASTER, */
  ROLE_USER,
  ROLE_SHOP,
  ROLE_COMERCIAL,
  ROLE_MASTER
];